In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
population_df = pd.read_csv("../Resources/NST-EST2021-alldata.csv", encoding="latin-1")
population_df.head(10)

,SUMLEV,REGION,DIVISION,STATE,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,NPOPCHG_2020,NPOPCHG_2021,...,NETMIG2020,NETMIG2021,RESIDUAL2020,RESIDUAL2021,RBIRTH2021,RDEATH2021,RNATURALINC2021,RINTERNATIONALMIG2021,RDOMESTICMIG2021,RNETMIG2021
0,10,0,0,0,United States,331449281,331501080,331893745,51799,392665,...,12247,244622,0,0,10.798957,10.352637,0.446319,0.737485,0.000000,0.737485
1,20,1,0,0,Northeast Region,57609148,57525633,57159838,-83515,-365795,...,-79429,-333592,-1024,-1151,9.950554,10.492070,-0.541516,0.977386,-6.794897,-5.817511
2,20,2,0,0,Midwest Region,68985454,68935174,68841444,-50280,-93730,...,-47266,-85268,-718,5156,10.860566,11.058248,-0.197682,0.549222,-1.786994,-1.237772
3,20,3,0,0,South Region,126266107,126409007,127225329,142900,816322,...,134454,770076,528,-3385,11.168835,10.777476,0.391359,0.886268,5.186064,6.072332
4,20,4,0,0,West Region,78588572,78631266,78667134,42694,35868,...,4488,-106594,1214,-620,10.767153,8.947910,1.819243,0.487570,-1.842880,-1.355309
5,40,3,6,1,Alabama,5024279,5024803,5039877,524,15074,...,3337,23380,-75,242,11.191613,12.890226,-1.698613,0.247201,4.398749,4.645950
6,40,4,9,2,Alaska,733391,732441,732673,-950,232,...,-2012,-3353,39,-54,12.667956,7.700425,4.967532,0.718033,-5.295151,-4.577118
7,40,4,8,4,Arizona,7151502,7177986,7276316,26484,98330,...,26791,97504,-3,-6,10.584669,10.469547,0.115121,0.619608,12.871739,13.491347
8,40,3,7,5,Arkansas,3011524,3012232,3025891,708,13659,...,1618,16840,-15,55,11.599962,12.671819,-1.071856,0.272932,5.304960,5.577892
9,40,4,9,6,California,39538223,39499738,39237836,-38485,-261902,...,-62562,-352960,858,-938,10.778412,8.441637,2.336775,0.364223,-9.329701,-8.965478

In [3]:
database_path = ("../SQLiteDatabase/Accidents_2021.db")
engine = create_engine(f"sqlite:///{database_path}")
conn = engine.connect()

In [5]:
population_df.to_sql("population", conn, schema=None, if_exists='append', index=False, index_label=None, chunksize=None, dtype=None, method=None)

IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: population.NAME
[SQL: INSERT INTO population ("SUMLEV", "REGION", "DIVISION", "STATE", "NAME", "ESTIMATESBASE2020", "POPESTIMATE2020", "POPESTIMATE2021", "NPOPCHG_2020", "NPOPCHG_2021", "BIRTHS2020", "BIRTHS2021", "DEATHS2020", "DEATHS2021", "NATURALINC2020", "NATURALINC2021", "INTERNATIONALMIG2020", "INTERNATIONALMIG2021", "DOMESTICMIG2020", "DOMESTICMIG2021", "NETMIG2020", "NETMIG2021", "RESIDUAL2020", "RESIDUAL2021", "RBIRTH2021", "RDEATH2021", "RNATURALINC2021", "RINTERNATIONALMIG2021", "RDOMESTICMIG2021", "RNETMIG2021") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [(10, '0', '0', 0, 'United States', 331449281, 331501080, 331893745, 51799, 392665, 893000, 3581986, 853448, 3433943, 39552, 148043, 12247, 244622, 0, 0, 12247, 244622, 0, 0, 10.798956715, 10.352637285, 0.4463194298, 0.7374854032, 0.0, 0.7374854032), (20, '1', '0', 0, 'Northeast Region', 57609148, 57525633, 57159838, -83515, -365795, 145067, 570592, 148129, 601644, -3062, -31052, 3314, 56046, -82743, -389638, -79429, -333592, -1024, -1151, 9.9505542424, 10.49207009, -0.541515847, 0.9773862288, -6.794897324, -5.817511095), (20, '2', '0', 0, 'Midwest Region', 68985454, 68935174, 68841444, -50280, -93730, 190941, 748166, 193237, 761784, -2296, -13618, 1678, 37835, -48944, -123103, -47266, -85268, -718, 5156, 10.860565615, 11.058247924, -0.197682309, 0.5492223651, -1.786994075, -1.23777171), (20, '3', '0', 0, 'South Region', 126266107, 126409007, 127225329, 142900, 816322, 345546, 1416400, 337628, 1366769, 7918, 49631, 6553, 112394, 127901, 657682, 134454, 770076, 528, -3385, 11.168834806, 10.777476122, 0.3913586842, 0.886268017, 5.1860643978, 6.0723324148), (20, '4', '0', 0, 'West Region', 78588572, 78631266, 78667134, 42694, 35868, 211446, 846828, 174454, 703746, 36992, 143082, 702, 38347, 3786, -144941, 4488, -106594, 1214, -620, 10.767153385, 8.9479104683, 1.8192429166, 0.4875701215, -1.842879521, -1.355309399), (40, '3', '6', 1, 'Alabama', 5024279, 5024803, 5039877, 524, 15074, 13410, 56320, 16148, 64868, -2738, -8548, -2, 1244, 3339, 22136, 3337, 23380, -75, 242, 11.191612649, 12.890226018, -1.698613369, 0.2472011033, 4.3987488922, 4.6459499954), (40, '4', '9', 2, 'Alaska', 733391, 732441, 732673, -950, 232, 2407, 9280, 1384, 5641, 1023, 3639, 21, 526, -2033, -3879, -2012, -3353, 39, -54, 12.667956214, 7.7004246769, 4.9675315368, 0.718032863, -5.295151094, -4.577118231), (40, '4', '8', 4, 'Arizona', 7151502, 7177986, 7276316, 26484, 98330, 18036, 76497, 18340, 75665, -304, 832, 167, 4478, 26624, 93026, 26791, 97504, -3, -6, 10.584668841, 10.469547405, 0.1151214358, 0.6196079202, 12.871738808, 13.491346728)  ... displaying 10 of 57 total bound parameter sets ...  (40, '4', '8', 56, 'Wyoming', 576851, 577267, 578803, 416, 1536, 1643, 6213, 1500, 6042, 143, 171, 4, 116, 279, 1252, 283, 1368, -10, -3, 10.748484088, 10.452654251, 0.2958298373, 0.2006798896, 2.1659588087, 2.3666386983), (40, 'X', 'X', 72, 'Puerto Rico', 3285874, 3281538, 3263584, -4336, -17954, 4549, 18537, 7324, 32710, -2775, -14173, -1561, -3781, 0, 0, -1561, -3781, 0, 0, 5.6643711149, 9.9952300354, -4.330858921, -1.155364254, 0.0, -1.155364254)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)